<?php

return [
    'durations' => [
        'monthly' => '+1 month',
        'weekly' => '+1 week',
        'lifetime' => null,
    ],
    'payment_method_types' => 'card',
    'front_settings' => [
        'general_settings' => [
            'splash_logo_url',
            'home_logo_url',
            'drawer_logo_url',
            'isChatHistoryEnable',
            'isCameraEnable',
            'isChatHistoryEnable',
            'isGuestLoginEnable',
            'isChatShow',
            'isImageGeneratorShow',
            'isTextCompletionShow',
            'privacy_policy',
            'isVoiceEnable',
            'isRTL',
            'refundLink',
            'rewardPoint',
            'chatgpt_api_key',
            'revenuecat_android_api_key',
            'revenuecat_ios_api_key',
            'free_chat_limit',
        ],
        'ads_settings' => [
            'admobile_publisher_id',
            'admobile_app_id',
            'open_ads_id',
            'rateapp_android_id',
            'rateapp_ios_id',
            'native_id',
            'ad_banner_android_id',
            'ad_banner_ios_id',
            'ad_reward_android_id',
            'ad_reward_ios_id',
            'add_interstitial_android_id',
            'add_interstitial_ios_id',
        ],
    ],
];
